load("@rules_cc//cc:defs.bzl",  "cc_test")

cc_test(
    name = "foo",
    srcs = ["foo.cc"],
)

cc_test(
    name = "bar",
    srcs = ["bar.cc"],
)

cc_test(
    name = "baz",
    srcs = ["foo.cc"],
)
