/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Foo */

#ifndef _Included_Foo
#define _Included_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Foo
 * Method:    calcNativeFoo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Foo_calcNativeFoo
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
