py_library(
    name = "linked_list",
    srcs = ["linked_list.py"],
)

py_test(
    name = "linked_list_test",
    srcs = ["linked_list_test.py"],
    deps = [":linked_list"],
    python_version = "PY3",
    srcs_version = "PY3",
)

py_test(
    name = "node_test",
    srcs = ["node_test.py"],
    deps = [":linked_list"],
    python_version = "PY3",
    srcs_version = "PY3",
)
